### ISSUE TITLE
Cancelling jobs not implemented

### ISSUE THREAD

**Issue by LourensVeen** [psnc-qcg/QCG-PilotJob#89]
There's a `qcg.pilotjob.api.manager.Manager.cancel()` method, but according to the documentation it always raises an exception. To avoid using up the rest of the core hours in the allocation on useless computation, I'd like to be able to shut down the other jobs by cancelling them if one of my jobs fails. I think this method would let me do that, could it be implemented? Ideally by first sending SIGTERM and then after 10s or so SIGKILL, but an immediate SIGKILL will work for the time being.

**Comment by pkopta** [comment]
Hi Lourens, indeed the `cancel` method is currently not supported - there was no interest in using this method. But if it's useful for you, I will try to implement this method in the next release.

**Comment by pkopta** [comment]
Hi Lourens, there is new pull request with job cancel functionality https://github.com/vecma-project/QCG-PilotJob/pull/94. It should be merged in the new release.

**Comment by LourensVeen** [comment]
That's great! I literally got my first "Request not implemented" yesterday evening :-). Thanks a lot!

**Comment by LourensVeen** [comment]
It looks like this PR caused a bug: `psutils` is not listed as a dependency in `setup.py`, so it doesn't get installed and QCG-PJ (current develop) errors out when you try to use it.

**Comment by pkopta** [comment]
Sorry - my mistake - i've changed the `reqs/requirements.txt` but forgot about `setup.py`. I've merged the fix into `develop` branch. Btw to prepare the release i've merged all the pr's to the develop so all the bugfixes you will find there.

**Comment by LourensVeen** [comment]
One of my colleagues has both a `setup.py` and a `requirements.txt` as well, and just [reads in the `requirements.txt` from `setup.py`](https://github.com/fair-workflows/nanopub/blob/main/setup.py#L33). I thought that was pretty clever, maybe that will also work here?

**Comment by pkopta** [comment]
That's indeed clever to unify requirements - but in qcg-pj case there is also `pytest` in requirements.txt - which is required for development but not necessary for deployment for regular users - I'm not sure it should be placed in setup.py

**Comment by LourensVeen** [comment]
In MUSCLE3 I have different sets of requirements in `setup.py`: `install_requires` has only the runtime dependencies, and then there's `tests_require` for pytest and such, and also `setup_requires` for `pytest-runner` and the dependencies for building the documentation. So it should be in there if you use `python setup.py test` to run your tests, but under a different heading.

This will change though, because setuptools is moving away from running tests and building docs (there aren't many active contributors, and they don't have the time to maintain it all) and is trying to focus only on building packages, so I'm planning to switch to `tox` at some point at least for running tests, and remove all that again...

**Comment by LourensVeen** [comment]
Since this was implemented and released, maybe it should be closed? Or do you want to leave it open for the `setup.py`/`requirements.txt` issue?
